### ISSUE TITLE
Duplicated 'checksum/session-secret' when imageUpload configured

### ISSUE THREAD

**Issue by rossigee** [hackmdio/codimd-helm#14]
Installing Helm chart using imageUpload values...

```
      Helm install failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
        line 38: mapping key "checksum/session-secret" already defined at line 37
```

Values are:

```
    codimd:
      database:
        host: ...
        username: codimd
        password: ...
      imageUpload:
        storeType: s3
        s3:
          bucket: ...
          accessKeyId: ...
          secretKey: ...
```
