### ISSUE TITLE
Image at values.yaml

### ISSUE THREAD

**Issue by pulpo** [hackmdio/codimd-helm#2]
Hi, 

The image that is being used as default at the values.yaml seems to be a private one

```yaml
image:
  registry: "nabo.codimd.dev"
  repository: "hackmdio/hackmd"
  # When you use export pdf with CJK character, please change the tag with postfix `-cjk`.
  # for example 2.1.0-cjk
  tag: "2.1.0"
  pullPolicy: IfNotPresent
  pullSecrets: []
#    - myRegistryKeySecretName

```

Any chance to make it public?

**Comment by pulpo** [comment]
I found the way to make it work, using the hackmdio/hackmd image from docker hub:

```yaml
image:
  registry: docker.io
  repository: hackmdio/hackmd 
  # When you use export pdf with CJK character, please change the tag with postfix `-cjk`.
  # for example 2.1.0-cjk
  tag: latest 
  pullPolicy: IfNotPresent
  pullSecrets: []
#    - myRegistryKeySecretName

```
