### ISSUE TITLE
Minio Config still needs s3bucket

### ISSUE THREAD

**Issue by belfhi** [hackmdio/codimd-helm#8]
Hello,
I set up codiMD with Helm and was quite happy with the results,
the deployment succeeded, with OAuth2 Authentication via Keycloak.

The only issue I still have is the image upload via Minio.
As far as I can tell from the documentation even minio needs the setting `s3bucket`
but I don't see an option in the Helm Chart.

**Comment by fewensa** [comment]
```yaml
codimd:
  security:
    sessionSecret: session_secret
  imageUpload:
    storeType: minio
    minio:
      endpoint: minio_host
      secure: true
      port: 443
      accessKey: abcdefg
      secretKey: abcdefg
    s3:
      accessKeyId: hack_hackmd_helm_config_bug    ###  hack
      bucket: hackmd      ### this is `s3bucket`
  imageStorePersistentVolume:
    enabled: false
```
